export const subjectDescription = {
  physics:
    "Physics is what it says on the tin - you have to analyse a range of data, from complex numerical problems to simple maths problems, and use basic maths to come to an answer. The important thing to know is that you don’t need any maths skills beyond that required for GCSE.This section really test your maths as much as it tests your ability solve problems. At the same time, you still need a strong grounding in percentages, proportions, basic formulas, and the like - because knowing them well helps you save time. There are also other ways of saving time, and we’ll go through some of those in this section. Whatever you do, work on your weaknesses first and practice as much as you can.",
  chemistry:
    "Chemistry is what it says on the tin - you have to analyse a range of data, from complex exquations to simple formulas , and try to use basic maths to come to an answer. The important thing to know is that you don’t need very complex knowledge of the chemistry to solve it just simple tricks will do perfectly . At the same time, you still need a strong grounding in percentages, proportions, basic formulas, and the like - because knowing them well helps you save time. There are also other ways of saving time, and we’ll go through some of those in this section. Whatever you do, work on your weaknesses first and practice as much as you can.",

  math: "Math is what it says on the tin - you have to analyse a range of data, from complex tables to simple maths problems, and use basic maths to come to an answer. The important thing to know is that you don’t need any maths skills beyond that required for GCSE.This section doesn’t really test your maths as much as it tests your ability to do things under timed pressure. At the same time, you still need a strong grounding in percentages, proportions, basic formulas, and the like - because knowing them well helps you save time. There are also other ways of saving time, and we’ll go through some of those in this section. Whatever you do, work on your weaknesses first and practice as much as you can.",

  biology:
    "Biology is what it says on the tin - you have to analyse a range of simple cell data, from complex tables to simple maths problems, and use basic maths to come to an answer. The important thing to know is that you don’t need any maths skills beyond that required for Matric.This section doesn’t really test your maths as much as it tests your ability to find simple and time saving solutions to complex problems. At the same time, you still need a strong grounding in percentages, proportions, basic formulas, and the like - because knowing them well helps you save time. There are also other ways of saving time, and we’ll go through some of those in this section. Whatever you do, work on your weaknesses first and practice as much as you can.",
};
